# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'cpaw.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow3(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(80, 170, 171, 51))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Black")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.label.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label.setTextFormat(QtCore.Qt.PlainText)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(80, 250, 171, 51))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Black")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setTextFormat(QtCore.Qt.PlainText)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(220, 30, 371, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe Script")
        font.setPointSize(28)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(20, 110, 641, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe MDL2 Assets")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(80, 330, 171, 51))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Black")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setTextFormat(QtCore.Qt.PlainText)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(80, 420, 231, 51))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Black")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setTextFormat(QtCore.Qt.PlainText)
        self.label_5.setObjectName("label_5")
        self.uname = QtWidgets.QTextEdit(self.centralwidget)
        self.uname.setGeometry(QtCore.QRect(430, 170, 231, 41))
        self.uname.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.uname.setObjectName("uname")
        self.opwd = QtWidgets.QLineEdit(self.centralwidget)
        self.opwd.setGeometry(QtCore.QRect(430, 250, 231, 41))
        self.opwd.setEchoMode(QtWidgets.QLineEdit.Password)
        self.opwd.setObjectName("opwd")
        self.npwd = QtWidgets.QLineEdit(self.centralwidget)
        self.npwd.setGeometry(QtCore.QRect(430, 340, 231, 41))
        self.npwd.setEchoMode(QtWidgets.QLineEdit.Password)
        self.npwd.setObjectName("npwd")
        self.ncpwd = QtWidgets.QLineEdit(self.centralwidget)
        self.ncpwd.setGeometry(QtCore.QRect(430, 420, 231, 41))
        self.ncpwd.setEchoMode(QtWidgets.QLineEdit.Password)
        self.ncpwd.setObjectName("ncpwd")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(430, 520, 81, 31))
        self.pushButton.setObjectName("pushButton")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        self.pushButton.clicked.connect(self.cpass)

    def cpass(self):
        usd=self.uname.toPlainText()
        opd=self.opwd.text()
        npd=self.npwd.text()
        ncpd=self.ncpwd.text()
        import os
        f=open("C:\\Users\sunny\OneDrive\Desktop\python\details.txt","a+")
        f.seek(0)
        li=f.readlines()
        di=dict()
        for i in li:
            u,p=i.split(':')
            p=p[:-1]
            di.update({u:p})
        
        try:
            if(di[usd]==opd):
                if(npd==ncpd):
                    f.seek(0)
                    f.truncate()
                    for i in di:
                        if(i!=usd):
                            st=i+':'+di[i]
                            f.write(st+'\n')
                    f.write(usd+':'+ncpd+'\n')
                    f.close()
                    self.label_6.setText("Password Changed Succssfully")
                else:
                    self.label_6.setText("Passwords didnot match :( Try again!")
            
            else:
                self.label_6.setText("Incorrect Old Password :( Try again!")
                    
        except:
            self.label_6.setText("Username not Rigistered!!") 
            
            

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Username:"))
        self.label_2.setText(_translate("MainWindow", "Old Password:"))
        self.label_3.setText(_translate("MainWindow", "DEMO WEBPAGE"))
        self.label_6.setText(_translate("MainWindow", "FILL THE BELOW DETAILS TO CHANGE PASSWORD"))
        self.label_4.setText(_translate("MainWindow", "New Password:"))
        self.label_5.setText(_translate("MainWindow", "Confirm Password:"))
        self.uname.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.pushButton.setText(_translate("MainWindow", "change"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow3()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
